name: stampede
description: A secure offline-first dashboard for managing stakeholder data.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  encrypt: ^5.0.1
  archive: ^3.3.6
  file_picker: ^6.1.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo.png
    - assets/avatar.png

windows:
  icon: assets/icon.ico