name: stampede
description: A secure offline-first dashboard for managing stakeholder data.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  encrypt: ^5.0.1
  archive: ^3.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

windows:
  icon: assets/icon.ico